
deployment:
tasks:
        - export REPOPATH=/home1/awboddos/repositories/3ds
    - export SITEPATH=/home1/awboddos/public_html/floor
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH